### ISSUE TITLE
didn't support django version 4.2.2

### ISSUE THREAD

**Issue by wshuaizki** [Xavier-Lam/wechat-django#22]
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/home/ubuntu/taillyfox/py_virtual_env/lib/python3.10/site-packages/django/utils/translation/__init__.py)

**Comment by Xavier-Lam** [comment]
It has been a long time since last time I maintained the project, this project was tested up to django 2.2.
It seemed `ugettext_lazy` has been removed since django 4. You should use `gettext_lazy` instead of  `ugettext_lazy`. 
You can either to make a local installation and change all `ugettext_lazy` to `gettext_lazy` or make an ugly monkey patch, assign `django.utils.translation.gettext_lazy` to `django.utils.translation.ugettext_lazy`.

There may be other problems since django has upgraded 2 major versions, be careful if you want to use this project in production environment.

Reference:
https://stackoverflow.com/a/71420374/4719118
